In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.12810752,  0.01904942,  0.2397489 ,  0.19267358, -0.00931333,
         0.2043608 ,  0.32355416, -0.00397903, -0.30916223, -0.3656299 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.08454537, 0.09794883, 0.12213716, 0.11652075, 0.09520976,
        0.11789054, 0.13281403, 0.09571899, 0.07054377, 0.06667072]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.1379986

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 13s 6ms/step - loss: 0.2971 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.1459 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1087 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0871 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0758 - accuracy: 0.9764


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0761 - accuracy: 0.9757 - 1s/epoch - 4ms/step


[0.07605397701263428, 0.9757000207901001]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.1339544e-08, 9.6981296e-08, 9.2958062e-06, 8.9646789e-04,
        8.2699139e-11, 2.5883173e-07, 1.4996403e-10, 9.9907231e-01,
        1.0071894e-06, 2.0544185e-05],
       [5.6017018e-09, 6.8099843e-04, 9.9930513e-01, 5.5402252e-06,
        1.1787955e-14, 8.3679315e-06, 4.2846420e-08, 1.6948880e-13,
        4.1223476e-08, 8.0692837e-16],
       [4.4953907e-07, 9.9950290e-01, 5.4562206e-05, 1.1582074e-05,
        7.0609112e-06, 8.0502286e-06, 1.9894260e-05, 3.0171551e-04,
        9.3356815e-05, 3.9124407e-07],
       [9.9970609e-01, 4.9016712e-08, 2.1250865e-04, 2.3152643e-06,
        9.9578415e-08, 7.1924683e-06, 5.0003775e-05, 8.2049282e-06,
        3.6220004e-07, 1.3157283e-05],
       [1.5695381e-06, 1.9559855e-06, 3.2399537e-05, 1.2825653e-07,
        9.9436980e-01, 1.8857973e-07, 5.8356272e-07, 1.3718102e-04,
        8.7089516e-05, 5.3692586e-03]], dtype=float32)>